CREATE DATABASE IF NOT EXISTS projeto_final_ppi;

USE projeto_final_ppi;

CREATE TABLE Anunciante (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Cpf VARCHAR(11) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  SenhaHash VARCHAR(255) NOT NULL,
  Telefone VARCHAR(20) NOT NULL
);

CREATE TABLE Anuncio (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Marca VARCHAR(50) NOT NULL,
  Modelo VARCHAR(50) NOT NULL,
  Ano INT NOT NULL,
  Cor VARCHAR(20),
  Quilometragem INT NOT NULL,
  Descricao TEXT,
  Valor DECIMAL(10,2) NOT NULL, 
  DataHora DATETIME DEFAULT CURRENT_TIMESTAMP,
  Estado VARCHAR(2),
  Cidade VARCHAR(100),
  IdAnunciante INT NOT NULL,
  FOREIGN KEY(IdAnunciante) REFERENCES Anunciante(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Interesse (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL,
  Telefone VARCHAR(20) NOT NULL,
  Mensagem TEXT,
  DataHora DATETIME DEFAULT CURRENT_TIMESTAMP,
  IdAnuncio INT NOT NULL,
  FOREIGN KEY(IdAnuncio) REFERENCES Anuncio(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Foto (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  IdAnuncio INT NOT NULL,
  NomeArqFoto VARCHAR(255) NOT NULL,
  FOREIGN KEY(IdAnuncio) REFERENCES Anuncio(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
